# slurm.conf
# Basic configuration file for a single-node Slurm setup in Docker

# CONTROLLER SETTINGS
ClusterName=rock
ControlMachine=localhost
ControlAddr=127.0.0.1
SlurmUser=rock

# PATHS
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/lib/slurmd
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldLogFile=/var/log/slurm/slurmctld.log

# AUTHENTICATION
AuthType=auth/munge
CryptoType=crypto/munge

# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_res
SelectTypeParameters=CR_CPU

# MANAGEMENT
AccountingStorageType=accounting_storage/none
JobAcctGatherType=jobacct_gather/none
SlurmctldPort=6817
SlurmdPort=6818
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
ProctrackType=proctrack/pgid
ReturnToService=1

# NODE CONFIGURATIONS
# Define a single compute node (the Docker container itself)
NodeName=localhost CPUs=2 State=UNKNOWN
PartitionName=normal Default=YES MaxTime=INFINITE State=UP 