#' @title Create Job Script
#' @description Creates an R script for running a job.
#' @param func_name Character string with the name of the function.
#' @param args List of arguments to pass to the function.
#' @param job_id Character string with the job ID.
#' @param db_path Character string with the path to the database.
#' @param required_packages Character vector with additional packages to load.
#' @param slurm_opts List with Slurm-specific options.
#' @return Character string with the job script.
#' @keywords internal
create_job_script <- function(func_name, args, job_id, db_path, 
                              required_packages = NULL, slurm_opts = list()) {
  # Create script lines
  script_lines <- c(
    "#!/usr/bin/env Rscript",
    "# Script generated by dsHPC",
    "",
    "# Load required libraries",
    "library(RSQLite)",
    "library(DBI)",
    ""
  )
  
  # Add required packages
  if (!is.null(required_packages) && length(required_packages) > 0) {
    script_lines <- c(script_lines, "# Load additional required packages")
    for (pkg in required_packages) {
      script_lines <- c(script_lines, paste0("library(", pkg, ")"))
    }
    script_lines <- c(script_lines, "")
  }
  
  # Add connection to database
  script_lines <- c(
    script_lines,
    "# Connect to the job database",
    paste0("con <- dbConnect(RSQLite::SQLite(), '", db_path, "')"),
    ""
  )
  
  # Add function to get job information
  script_lines <- c(
    script_lines,
    "# Function to get job arguments",
    "get_job_args <- function(con, job_id) {",
    "  query <- paste0(\"SELECT args FROM jobs WHERE job_id = '\", job_id, \"'\");",
    "  result <- dbGetQuery(con, query)",
    "  if (nrow(result) == 0) {",
    "    stop(\"Job not found\")",
    "  }",
    "  unserialize(jsonlite::base64_dec(result$args[1]))",
    "}",
    ""
  )
  
  # Add function to update job status
  script_lines <- c(
    script_lines,
    "# Function to update job status",
    "update_job_status <- function(con, job_id, status, error_message = NA, completed = FALSE) {",
    "  query <- paste0(\"UPDATE jobs SET status = '\", status, \"',\",",
    "                  \" error_message = '\", gsub(\"'\", \"''\", as.character(error_message)), \"',\",",
    "                  \" completed = \", as.integer(completed), \",\",",
    "                  \" last_updated = datetime('now') \",",
    "                  \"WHERE job_id = '\", job_id, \"'\")",
    "  dbExecute(con, query)",
    "}",
    ""
  )
  
  # Add function to store job result
  script_lines <- c(
    script_lines,
    "# Function to store job result",
    "store_job_result <- function(con, job_hash, result) {",
    "  # First check if a result with this hash already exists",
    "  query <- paste0(\"SELECT COUNT(*) AS count FROM job_results WHERE job_hash = '\", job_hash, \"'\")",
    "  result_exists <- dbGetQuery(con, query)$count > 0",
    "  ",
    "  # Serialize the result and encode to base64",
    "  serialized_result <- jsonlite::base64_enc(serialize(result, NULL))",
    "  ",
    "  if (result_exists) {",
    "    # Update existing result",
    "    query <- paste0(\"UPDATE job_results SET result = '\", serialized_result, \"', \",",
    "                    \"last_updated = datetime('now') \",",
    "                    \"WHERE job_hash = '\", job_hash, \"'\")",
    "  } else {",
    "    # Insert new result",
    "    query <- paste0(\"INSERT INTO job_results (job_hash, result, created_at, last_updated) \",",
    "                    \"VALUES ('\", job_hash, \"', '\", serialized_result, \"', \",",
    "                    \"datetime('now'), datetime('now'))\")",
    "  }",
    "  ",
    "  dbExecute(con, query)",
    "}",
    ""
  )
  
  # Add function to get job hash
  script_lines <- c(
    script_lines,
    "# Function to get job hash",
    "get_job_hash <- function(con, job_id) {",
    "  query <- paste0(\"SELECT object_hash FROM jobs WHERE job_id = '\", job_id, \"'\")",
    "  result <- dbGetQuery(con, query)",
    "  if (nrow(result) == 0) {",
    "    stop(\"Job not found\")",
    "  }",
    "  result$object_hash[1]",
    "}",
    ""
  )
  
  # Generate the main job execution code
  script_lines <- c(
    script_lines,
    "# Main execution",
    paste0("job_id <- '", job_id, "'"),
    paste0("func_name <- '", func_name, "'"),
    "",
    "# Update job status to RUNNING",
    "update_job_status(con, job_id, 'RUNNING')",
    "",
    "# Get job hash for storing result",
    "job_hash <- get_job_hash(con, job_id)",
    "",
    "# Get job arguments",
    "args <- get_job_args(con, job_id)",
    "",
    "# Execute the job",
    "tryCatch({",
    "  # Get the function",
    "  func <- get(func_name, mode = 'function')",
    "  ",
    "  # Execute the function with the provided arguments",
    "  result <- do.call(func, args)",
    "  ",
    "  # Store the result (always store in cache)",
    "  store_job_result(con, job_hash, result)",
    "  ",
    "  # Update job status to COMPLETED",
    "  update_job_status(con, job_id, 'COMPLETED', completed = TRUE)",
    "  ",
    "  # Print message for logs",
    "  cat('Job completed successfully: ', job_id, '\\n')",
    "}, error = function(e) {",
    "  # Update job status to FAILED",
    "  update_job_status(con, job_id, 'FAILED', error_message = as.character(e), completed = TRUE)",
    "  ",
    "  # Print error for logs",
    "  cat('Job failed: ', job_id, '\\n')",
    "  cat('Error: ', as.character(e), '\\n')",
    "})",
    "",
    "# Close database connection",
    "dbDisconnect(con)"
  )
  
  # Join all lines and return
  paste(script_lines, collapse = "\n")
} 